stages:
  - validate
  - build

validate:
  stage: validate
  image: node:22-alpine
  script:
    - cd app
    - npm ci
    - node --check server.js

docker-build:
  stage: build
  image: docker:27-cli
  services:
    - name: docker:27-dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker build -t gitops-demo-api:ci ./app
